data:
  root_dir:  '/mounts/Datasets3/2024-2025-ChallengePlankton/'
  trainpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/train/'
  testpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/test/'
  batch_size: 32
  num_workers: 6
  valid_ratio: 0.1 #changed from 0.2 to 0.1 because the dataset is quite large
  patch_size: [300,300]
  quick_test: false
optim:
  algo: AdamW
  params:
    lr: 0.0005
    weight_decay: 0.0001
scheduler:
  class: CosineAnnealingLR
  params:
    T_max: 8  # Nombre d'époques pour un cycle
    eta_min: 1e-6

nepochs: 4
# loss: "CrossEntropyLoss"
loss : "BCEWithLogitsLoss"
#pos_weight: 19.63  # Calculé comme (num_negatives / num_positives) avec environ 5% de positif. Put at 1 to desactivate
pos_weight: 1 #reduced the value to avoid instability
logging:
  wandb: 
    project: "ChallengePlankton"
    entity: "Random Predictions 2"  # Remplace par ton nom d'utilisateur ou celui de ton organisation
  logdir: "./logs"  # Emplacement des logs locaux

model:
  class: EfficientNetB3Segmentation
  input_channels: 1  # Modify based on your input data
  num_classes: 1     # Binary segmentation

test:
  model_path: 'logs/EfficientNetB3Segmentation_0/'
  model_name: 'best_model.pt'
  model_config: 'config.yaml'


