# YOAT GOAT Edition - Optimized
data:
  root_dir: '/mounts/Datasets3/2024-2025-ChallengePlankton/'
  trainpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/train/'
  testpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/test/'
  batch_size: 64  
  num_workers: 8
  valid_ratio: 0.1
  patch_size: [256, 256]  
  quick_test: false

optim:
  algo: AdamW
  params:
    lr: 0.001   # Possible augmentation à 0.0015 pour ConvNeXt
    weight_decay: 0.001  # Éviter overfitting

scheduler:
  class: CosineAnnealingWarmRestarts
  params:
    T_0: 3  
    T_mult: 2
    eta_min: 1e-6

nepochs: 12  # Augmenté pour stabiliser l’apprentissage avec les nouvelles transfo
pos_weight: 1

loss:
  name: "TverskyLoss"
  alpha: 0.4 
  beta: 0.6
  
logging:
  wandb:
    project: "ChallengePlankton"
    entity: "Random_Predictions_2"
  logdir: "./logs"

model:
  class: UNet  # Unet avec RegNetY comme encodeur
  encoder:
    model_name: timm-regnety_032  # RegNetY-3.2GF, supporté par SMP

# Désactiver si pas de ré-entrainement
#pretrained_model: "logs/UNet_10/best_model.pt"
#current best is UNet_10.

test:
  model_path: 'logs/RegNetY_1/'
  model_name: 'best_model.pt'
  model_config: 'config.yaml'
