data:
  root_dir: '/mounts/Datasets3/2024-2025-ChallengePlankton/'
  trainpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/train/'
  testpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/test/'
  batch_size: 64  # Ajustable selon la VRAM
  num_workers: 8
  valid_ratio: 0.1
  patch_size: [256, 256]
  quick_test: False
  transform_type: "light-optimal"

optim:
  algo: AdamW
  params:
    lr: 0.0003
    weight_decay: 0.0001

scheduler:
  class: CosineAnnealingLR
  params:
    T_max: 200  # Mettre le nombre total d'epochs
    eta_min: 0.00001

nepochs: 200  # Augmenté pour convergence optimale
pos_weight: 1

loss:
  name: "TverskyLoss"
  alpha: 0.6
  beta: 0.4

logging:
  wandb:
    project: "ChallengePlankton"
    entity: "Random_Predictions_2"
  logdir: "./logs"

model:
  class: Segformer
  encoder:
    model_name: "tu-swinv2_small_window8_256"
  decoder_segmentation_channels: 256
  in_channels: 1
  classes: 1
