data:
  root_dir: '/mounts/Datasets3/2024-2025-ChallengePlankton/'
  trainpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/train/'
  testpath: '/mounts/Datasets3/2024-2025-ChallengePlankton/test/'
  batch_size: 2
  num_workers: 8
  valid_ratio: 0.2
  patch_size: [256,256]
  quick_test: true
  augmented_data: true

optim:
  algo: AdamW
  params:
    lr: 0.0005
    weight_decay: 0.02

scheduler:
  class: CosineAnnealingWarmRestarts
  params:
    T_0: 4
    T_mult: 1
    eta_min: 0.000001

nepochs: 10
pos_weight: 1

loss:
  name: FocalTverskyLoss
  alpha: 0.4   # alpha <  beta
  beta: 0.6
  gamma: 1.3

logging:
  wandb:
    project: "ChallengePlankton"
    entity: "Random_Predictions_2"
  logdir: "./logs"

model:
  class: EfficientNetB3Segmentation
  encoder:
    model_name: resnet18
